Disney_Characters_API/Models/DisneyDescription.cs
using System;
namespace Disney_Characters_API.Models
{
	public class DisneyDescription
	{
        public int _id { get; set; }
        public List<string> Films { get; set; }
        public List<string> ShortFilms { get; set; }
        public List<string> TvShows { get; set; }
        public List<string> VideoGames { get; set; }
        public List<string> ParkAttractions { get; set; }
        public List<string> Allies { get; set; }
        public List<string> Enemies { get; set; }
        public string SourceUrl { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string Url { get; set; }
        public int __v { get; set; }
    }
}

Disney_Characters_API/Models/DisneyRoot.cs
using System;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Disney_Characters_API.Models
{
	public class DisneyRoot
	{
        public Info Info { get; set; }
        public List<DisneyDescription> Data { get; set; }
    }
}

Disney_Characters_API/Models/ErrorViewModel.cs
namespace Disney_Characters_API.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Disney_Characters_API/Models/Info.cs
using System;
namespace Disney_Characters_API.Models
{
	public class Info
	{
        public int Count { get; set; }
        public int TotalPages { get; set; }
        public string? PreviousPage { get; set; }
        public string? NextPage { get; set; }
    }
}

Disney_Characters_API/Controllers/DisneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Disney_Characters_API.Models;
using static System.Net.WebRequestMethods;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Disney_Characters_API.Controllers
{
    public class DisneyController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index([FromQuery(Name = "url")] string resourceUrl = "http://api.disneyapi.dev/character")
        {
            var client = new HttpClient();


            var disneyUrl = resourceUrl;



            var disneyResponce = client.GetStringAsync(disneyUrl).Result;

            var disneyRoot = JsonConvert.DeserializeObject<DisneyRoot>(disneyResponce);
            return View(disneyRoot);

        }
        
    }
}

Disney_Characters_API/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Disney_Characters_API.Models;

namespace Disney_Characters_API.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Disney_Characters_API/Views/Disney/Index.cshtml
@model DisneyRoot


<h1> Disney Characters</h1>

<div class="next-button" >
    @if (@Model.Info.PreviousPage != null)
    {
        <a asp-action="Index" asp-route-url="@Model.Info.PreviousPage" class="next-button">Previous Page</a>
    }
    @if (@Model.Info.NextPage != null)
    {
        <a asp-action="Index" asp-route-url="@Model.Info.NextPage" class="next-button">Next Page</a>
    }
</div>


<div class="img-size">
    @foreach (var character in Model.Data)
        {
            <ul>

                <li>Character Name: @character.Name</li>
                <li>Character ID# : @character._id </li>
                
                <li> character Created Date & Time : @character.CreatedAt</li>
                <li class="img"> @character Image: <img src=@character.ImageUrl height="150vh" width="150vh" > </li>

            </ul>
            
        }


   

   

</div>






<div class="next-button" >
    @if (@Model.Info.PreviousPage != null)
    {
        <a asp-action="Index" asp-route-url="@Model.Info.PreviousPage" class="next-button">Previous Page</a>
    }
    @if (@Model.Info.NextPage != null)
    {
        <a asp-action="Index" asp-route-url="@Model.Info.NextPage" class="next-button">Next Page</a>
    }
</div>
<h2>   @Model.Info.TotalPages  </h2>

 

Disney_Characters_API/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 >Welcome To Disney</h1>
    <p>Learn All About Disney Characters                  </p>

   




</div>
      
        

Disney_Characters_API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Disney_Characters_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Disney_Characters_API.styles.css" asp-append-version="true" />

</head>
<body>  
    <header>
        <nav class="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Disney_Characters_API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item2">
                            <a class="nav-link " asp-area="" asp-controller="Disney" asp-action="Index">Disney</a>
                        </li>
                    </ul> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Disney_Characters_API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>